apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lionpay

resources:
  - ../../base

images:
  - name: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/lionpay-auth
    newTag: "release"
  - name: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/lionpay-wallet
    newTag: "release"

commonLabels:
  environment: prod

patches:
  - path: hpa-patch.yaml

replicas:
  - name: auth-deployment
    count: 3
  - name: wallet-deployment
    count: 3
