apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: t4g-ondemand
spec:
  template:
    metadata:
      labels:
        type: karpenter
        provisioner: t4g-ondemand
        capacity-type: on-demand
    spec:
      requirements:
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t4g"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2", "4", "8"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: t4g
  limits:
    cpu: ${node_pool_cpu_limit}
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
