apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  AWS_REGION: "ap-northeast-2"
  DYNAMODB_TABLE_NAME: "LionpayAuthDev"
  JWT_ISSUER: "lionpay-auth"
  JWT_AUDIENCES: "lionpay-app,lionpay-management"
  OTEL_SERVICE_NAME: "lionpay-auth"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-k8s-monitoring-alloy-receiver.monitoring:4318/"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wallet-config
data:
  AWS_REGION: "ap-northeast-2"
  WALLETDB_CLUSTER_ENDPOINT: "qbtognuqdrfr2ip5op6wrj3diu.dsql.ap-northeast-2.on.aws"
  JWT_ISSUER: "lionpay-auth"
  JWT_AUDIENCES: "lionpay-app,lionpay-management"
  OTEL_SERVICE_NAME: "lionpay-wallet"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-k8s-monitoring-alloy-receiver.monitoring:4318/"
