apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lionpay

resources:
  - namespace.yaml
  - service-account.yaml
  - secret.yaml
  - configmap.yaml
  - auth-service.yaml
  - auth-deployment.yaml
  - wallet-service.yaml
  - wallet-deployment.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
