apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lionpay

resources:
  - ../../base

images:
  - name: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/lionpay-auth
    newTag: "latest"
  - name: 727646470302.dkr.ecr.ap-northeast-2.amazonaws.com/lionpay-wallet
    newTag: "latest"

commonLabels:
  environment: dev

patches:
  - path: hpa-patch.yaml
